### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by horseinthesky** [nvim-treesitter/nvim-treesitter-textobjects#100]
**Describe the bug**
I am trying to set up lazy loading of treesitter with `packer.nvim` and there is a race condition with doing so.
As a result keymapping for `textobjects` are not loaded.

**To Reproduce**
A piece of `packer` config:
```
  use {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate",
    requires = {
      {
        "nvim-treesitter/playground",
        after = "nvim-treesitter",
        cmd = { "TSPlaygroundToggle", "TSHighlightCapturesUnderCursor" },
      },
      {
        "nvim-treesitter/nvim-treesitter-textobjects",
        module = "nvim-treesitter-textobjects",
        after = "nvim-treesitter",
      },
    },
    event = "BufRead",
    config = function()
      require "config.treesitter"
    end,
  }
```

`config.treesitter` file:
```
local swap_next, swap_prev = (function()
  local swap_objects = {
    c = "@class.outer",
    f = "@function.outer",
    b = "@block.outer",
    s = "@statement.outer",
    p = "@parameter.inner",
    m = "@call.outer",
  }

  local n, p = {}, {}
  for key, obj in pairs(swap_objects) do
    n[string.format("<leader>s%s", key)] = obj
    p[string.format("<leader>S%s", key)] = obj
  end

  return n, p
end)()

require("nvim-treesitter.configs").setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
    disable = { "yaml" },
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<enter>",
      node_incremental = "<enter>",
      node_decremental = "<bs>",
    },
  },
  textobjects = {
    select = {
      enable = true,
      -- Automatically jump forward to textobj, similar to targets.vim
      lookahead = true,
      keymaps = {
        -- You can use the capture groups defined in textobjects.scm
        ["oc"] = "@class.outer",
        ["ic"] = "@class.inner",
        ["of"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ob"] = "@block.outer",
        ["ib"] = "@block.inner",
        ["ol"] = "@loop.outer",
        ["il"] = "@loop.inner",
        ["os"] = "@statement.outer",
        ["is"] = "@statement.inner",
        ["oC"] = "@comment.outer",
        ["iC"] = "@comment.inner",
        ["om"] = "@call.outer",
        ["im"] = "@call.inner",
      },
    },
    swap = {
      enable = true,
      swap_next = swap_next,
      swap_previous = swap_prev,
    },
    move = {
      enable = true,
      set_jumps = true, -- whether to set jumps in the jumplist
      goto_next_start = {
        ["]m"] = "@function.outer",
        ["]]"] = "@class.outer",
      },
      goto_next_end = {
        ["]M"] = "@function.outer",
        ["]["] = "@class.outer",
      },
      goto_previous_start = {
        ["[m"] = "@function.outer",
        ["[["] = "@class.outer",
      },
      goto_previous_end = {
        ["[M"] = "@function.outer",
        ["[]"] = "@class.outer",
      },
    },
  },
  playground = {
    enable = true,
    disable = {},
    updatetime = 25,
    persist_queries = false,
  },
}
```

As far as I understand what is going on is:
* `treesitter` is loaded (on `BufRead`) with the keymappings.
* `playground` and `textobjects` are loaded AFTER keymappings were set up and as a result no keymapping are actually appied to the plugin.

**Expected behavior**
Keymapping from `config.treesitter` must be applied to the plugin.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check                                                                                                           
========================================================================                                                               
## Installation                                                                                                                        
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall) 
  - OK: `node` found v14.17.1 (only needed for :TSInstallFromGrammar)                                                                  
  - OK: `git` executable found.                                                                                                        
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }                                                   
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.      
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.6.0-dev+116-g35041432b
```

Is there a way to lazy load the plugin with `packer.nvim`?

**Comment by kkanarios32** [comment]
I had the same issue. The workaround I came up with was just calling the config function when loading the textobjects instead of treesitter.

**Comment by horseinthesky** [comment]
I ended calling:
```
require "nvim-treesitter-textobjects"
```
before
```
require("nvim-treesitter.configs").setup {}
```
inside `"config.treesitte`

Not sure it is the best option but it works at least.

**Comment by arsham** [comment]
I moved loading the config to the textobjects section and it worked for me.
```lua
use {
    'nvim-treesitter/nvim-treesitter',
    requires = {
        {
            'nvim-treesitter/nvim-treesitter-textobjects',
            after = 'nvim-treesitter',
            config = function() require('settings.treesitter') end,
        },
    },
    -- initially the config setting was here.
    run = ':TSUpdate',
    event = { 'BufRead', 'BufNewFile', 'InsertEnter' },
}
```

It's not ideal, but the mappings are applied at the right time.

**Comment by horseinthesky** [comment]
Yeah. Both workarounds are fine. I don't think there is more to discuss.
