### ISSUE TITLE
After selecting outer, allow an inner select to go back instead of jump ahead

### ISSUE THREAD

**Issue by npezza93** [nvim-treesitter/nvim-treesitter-textobjects#125]
In ruby you have blocks that can look like the following:
```ruby
foo.each do |item|
  item
end

foo.each { |item| item }
```

`@block.outer` in the first case would cover `do..end` including the `do` and `end` and would cover the brackets and everything inside the brackets in the second. (Note in the second example the brackets dont have to be on the same line)

If you were to do a visual selection of the outer and then cancel, your cursor would be moved to the very end of the block(makes sense since this is how other text objects work like word). Your cursor would be on the `d` in `end` in the first example and `}` in the second.

If you then went to select `@block.inner` you jump to the next instance rather than doing the inner of the outer your cursor is on

If this isnt possible, feel free to close. Appreciate your work on this project!

https://user-images.githubusercontent.com/5059927/135736793-2c036edb-4adf-4b29-a2db-7a3cc425f722.mov

.

**Comment by stsewd** [comment]
I think this is a very specific case. Another way would be to allow having text objects to do a lookahead and others to do a lookback https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/737b0a36059bc672fe767a40df9cd6d238df5f2e/lua/nvim-treesitter-textobjects.lua#L32

Similar to targets.vim https://github.com/wellle/targets.vim#next-and-last-quote (`in{object}`/`il{object}` -- next/last)

**Comment by kiyoon** [comment]
This is related to #335. I think a possible solution is whenever calling `@*.inner` we call `@*.outer` and search within that range as the highest priority. Otherwise, inner will select wrong parts unless you are actually inside that context and it will not work when you're on the function definition etc.

**Comment by kiyoon** [comment]
Closing as completed in #386
