### ISSUE TITLE
Implement LHS/RHS of assignment operator

### ISSUE THREAD

**Issue by romgrk** [nvim-treesitter/nvim-treesitter-textobjects#15]
Like [this](https://github.com/romgrk/equal.operator) but with treesitter support.

**Comment by theHamsta** [comment]
I guess this either requires: https://github.com/nvim-treesitter/nvim-treesitter/pull/493
or we just have a assignment textobject whose "inner" is either rhs or lhs.

For python:
```
(assignment
 left: (_) @lhs.inner
 right: (_) @rhs.inner)
```
or 
```
(assignment
 left: (_) @assignment.inner
 right: (_) @assignment.inner) @assignment.outer
```

**Comment by kiyoon** [comment]
Closing as completed in #386
