### ISSUE TITLE
Cannot use `textobjects` after commit 2623fc7

### ISSUE THREAD

**Issue by captainko** [nvim-treesitter/nvim-treesitter-textobjects#167]
PR: https://github.com/nvim-treesitter/nvim-treesitter/pull/2272
```
|| Error detected while processing FileType Autocommands for "*":
|| E5108: Error executing lua ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:59: attempt to concatenate local 'query' (a table value)
|| stack traceback:
|| 	...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:59: in function 'attach'
|| 	...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:458: in function 'attach_module'
|| 	...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:481: in function 'reattach_module'
|| 	[string ":lua"]:1: in main chunk
|| No localrc found
```

**Comment by clason** [comment]
Did you make sure to reinstall the parser (restarting Neovim) and upgrade to the latest version of both nvim-treesitter and nvim-treesitter-textobjects?

**Comment by clason** [comment]
Note that the capture names have changed, so you may have to adapt the mappings in your setup.

**Comment by kylo252** [comment]
Removing this snippet fixed it for me

```lua
      -- Or you can define your own textobjects like this
      ["iF"] = {
        python = "(function_definition) @function",
        cpp = "(function_definition) @function",
        c = "(function_definition) @function",
      },
```
Which probably should've been marked as a breaking change in https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/2623fc7e82c876c394769e4ab9dff8bb2525e58f

**Comment by clason** [comment]
@MunifTanjim can you add a "Rosetta stone" for your textobject queries (old -> new)?

**Comment by clason** [comment]
This is not related to the linked PR; see https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/2623fc7e82c876c394769e4ab9dff8bb2525e58f

**Comment by clason** [comment]
The ability to specify custom directly in your mappings was removed (because it never really worked), so you need to adapt your config accordingly.

(This should have been marked as breaking, but we hadn't properly set up workflows around this.)

**Comment by captainko** [comment]
@clason I cannot believe this. I use customized mappings all the time :((.

**Comment by captainko** [comment]
@clason, thanks for clarifying the issue for me.

**Comment by clason** [comment]
Note: customized _mappings_  still work, it's just that you can't specify custom _captures_  in those mappings directly; you first have to define them in a local query. The PR description and the updated README explain what you have to do now to get the same mappings back.
