### ISSUE TITLE
@parameter.inner/@parameter.outer for R not working properly

### ISSUE THREAD

**Issue by mllg** [nvim-treesitter/nvim-treesitter-textobjects#184]
Thanks for the work, I love the plugin. I still have some problems with R though. Consider the following examples (`|` is cursor position, lookahead is enabled):

```r
# parameter.inner matches "y" instead of "y = 2"
f = function(x, |y = 2) {
  x^y
}

# parameter.inner does not match
f = function(x, y = |2) {
  x^y
}

# parameter.outer does match "(x, y = 2)" instead of "x,"
f = function(|x, y = 2) {
  x^y
}


# parameter.outer does match "(x, y = 2)" instead of ", y = 2"
f = function(x, |y = 2) {
  x^y
}

# parameter.inner matches "na.rm" instead of "na.rm = TRUE"
# parameter.outer matches "na.rm" instead of ", na.rm = TRUE"
mean(x, |na.rm = TRUE)

# parameter.inner does not match
# parameter.outer does not match
mean(x, na.rm = |TRUE)

# parameter.inner does not match
# parameter.outer does not match
list(
  2|, 
  3
)

# @parameter.inner matches "x" instead of "x = 2"
# @parameter.outer matches "x" instead of "x = 2,"
list(
  |x = 2,
  y = 3
)

# @parameter.inner matches "y" instead of "x = 2"
# @parameter.outer matches "y" instead of "x = 2,"
list(
  x = |2,
  y = 3
)
```

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . ✓ . 
  - bibtex         ✓ . ✓ ✓ . 
  - latex          ✓ . ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by milanglacier** [comment]
I agree with you:
facing the same problem.
It seems that the R parser has a problem in parsing the arguments:

`|` is the cursor position:

```

a = rnorm(1, 1|0)
# define a function b in R
b = function(a, b) {
    print("cat")
}

# after typing daa, it becomes

a = rnorm(1, 10)
b = function| {
    print("cat")
}

# The correct result shoud be

a = rnorm(1)
b = function(a,b) {
    print("cat")
}
```

**Comment by mllg** [comment]
Thanks for your patch, many of the above issues have been resolved with the latest version, but unfortunately at least one problem remains while working with named arguments:

```r
# parameter.inner matches "x" in mean(x) instead of "y = 2"
f = function(x, |y = 2) {
  mean(x)^y
}

# parameter.inner does not match / seeking for match in next lines
list(1, |a = 1, b = 2)
```

Can you reopen or do you want me to file a new issue?

**Comment by theHamsta** [comment]
better a new issue with the concrete example
