### ISSUE TITLE
Easier option to define mapping manually

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter-textobjects#20]
Hey guys,

thank you very much for your great work on all the treesitter features! I highly appreciate it! :pray: 

**Is your feature request related to a problem? Please describe.**

I must admit that I was never a friend of letting a plugin doing the key mappings for me. Also if it allows me to define a configuration option to define the key-combo to use. I feel like having less control, it becomes unstructured and ugly. At least that is my view. Unfortunately it seems to become a pattern for the more recent Lua'ish plugins to push for this kind of mappings.
So I denied to use the map definitions within the initialization step of this plugin. I'm adding them manually by myself where they belong to (from my perspective). Unfortunately this results in incredible long lines which look like this for example:

```vim
vnoremap <silent> af :<C-u>lua require'nvim-treesitter.textobjects.select'.select_textobject('@function.outer')<CR>
```

Talking about code quality this results into a fail that is hard to read, because 80% is equal boilerplate code. It is hard to see what is the actual relevant configuration here.

**Describe the solution you'd like**
I wanted to ask if you guys are willed to add a simple command for each of those exposed functions. Just something as simple as `api.nvim_command('command! TSTextObjectSelect lua require....`. This would make it slightly easier to add such mappings by hand, removing a lot of the boilerplate.

---

I'm also open to get suggestions how I could improve my mappings else.
Thank you very much in advanced!

**Comment by theHamsta** [comment]
> it becomes unstructured and ugly.

I find viml unstructured and ugly.

It's obvious that you can access a vim plugin better with viml and a Lua plugin better with Lua. When you want to write your own mapping you can also structure repeating structures in the way you find estetic. Lua plugins are meant to be configured by Lua. 

Plugin authors should not be forced to copy all their functions to a vim command (and potentially litter the users command) just because viml makes it a pain to abstract away repeating structures. I guess there will soon be a way to directly set keymaps for Lua functions.

**Comment by weilbith** [comment]
You have a point. 
But it doesn't change much. The core principle that I find ugly is to define the mappings within the configuration dictionaries. This concept is independent of the used language. It just might look like it, because Lua plugins have a higher percentage to follow this principle. My wild guess is that this eventually caused by exactly that reason: it is horrible to write mappings in Lua that are nice write and easy on the eye to read. But I hope that Lua has higher potential to offer improvements to that.

PS: Thank you very much for your PR!

**Comment by theHamsta** [comment]
I guess nvim will mitigate language boundary and make it easier to set mappings in Lua directly.

The motivation of the dictionaries is to group a certain group of mappings and set and unset them exactly when they are needed. Also for personal dotfiles such dictionaries allow you to write some logic and after that just "keysequence" -> "function"

**Comment by weilbith** [comment]
> The motivation of the dictionaries is to group a certain group of mappings and set and unset them exactly when they are needed. Also for personal dotfiles such dictionaries allow you to write some logic and after that just "keysequence" -> "function"

Hmm. I must admit that this relates to a subject I'm thinking of the last days. On one side the approach pretty much as you described. The other would be to define mappings in groups. A group is focused on a specific topic. These mappings make use of the functionality of multiple plugins. This group makes sense as human, it is easy to build combos with the same beginning etc. Taking the example of a group that relates to comments. You want to comment or un-comment targets, change comment formats, generate comments/inlinedocs based on code, highlight them temporally, ... And I would consider that comments are not a big group/topic and their usage can be discussed. But I would deny to use a single plugin that provides all of these features. And also not here listed, these features can be also built-in (e.g. think of tags). Having all these mappings distributed everywhere seems horrible. Sometime you might switch one plugin for another that provides the same basic feature idea. The mapping should stay, just the part to execute changes.

Both approaches follow different design/architecture principles. Taking the Single-Responsibility- and Open-Closed-Principles as examples. It is the question how does the user use his configuration as a piece of software. Who are the actors and responsibilities in this game? Is it more worth to have self-contained units with flat interfaces which do not create dependencies making it easy exchangeable. Or is a configuration more about understanding, usability and readability.

I'm still thinking about it. There are a lot of arguments and considerations. At least from my side.

**Comment by theHamsta** [comment]
When you just set the mappings you decide on them. The mappings of the plugin try to be intelligent. E.g. only set when the funcionality is available and automatically unset the mapping once you disable it (`TSDisable*`)

With the commands everybody should now be able to choose their preference. :slightly_smiling_face:

**Comment by weilbith** [comment]
Thanks for your openness and the nice discussion. :hugs: 
Still in the phase to figure out how my future setup with lua only(?) should look like. :shrug:

**Comment by theHamsta** [comment]
If you're fine with using globals you can also define shortcuts for certain lua modules to use them in viml.
```
tsselect = require'nvim-treesitter.textobjects.select

>Still in the phase to figure out how my future setup with lua only(?) should look like. shrug
