### ISSUE TITLE
Add "surrounding function" text object

### ISSUE THREAD

**Issue by mawkler** [nvim-treesitter/nvim-treesitter-textobjects#206]
[dsf.vim](https://github.com/AndrewRadev/dsf.vim) adds the commands dsf and csf to "delete surrounding function" and "change surrounding function", respectively. Would this be possible to implement as a feature in nvim-treesitter-textobjects?

Just like in dsf.vim, I suggest two different text objects to deal with the case where the cursor is inside another function call, as discussed here AndrewRadev/dsf.vim/issues/2. Basically here's the idea:

```txt
       cursor position
            |
            v
           ....
baz = bar( foo( baz ) )
           └───┘   └┘     <-- deleted text on dsf
      └───┘          └┘   <-- deleted text on dsF
```

`csf` deletes the function call, but not the parentheses, and puts you in insert mode before the opening parentheses. Here's an example to illustrate, where the cursor first is on the word `foo`, and is then represented by `|` after putting you in insert mode:

```txt
foo(bar)

|(bar)
```

`csF` behaves the same way as `csf` but targets the same function as `dsF` in the first example.

**Comment by pogopaule** [comment]
I've been trying to write a query for that but did not succeed.
For those who are interested in this topic, there is a similar discussion over at https://github.com/kylechui/nvim-surround/issues/60

**Comment by kylechui** [comment]
I will be looking into this; it should be possible now that I'm adding generic queries support to `nvim-surround`.

**Comment by kylechui** [comment]
If anybody's interested, continued discussion on how this feature is going to be generalized and implemented for `nvim-surround` [will occur here](https://github.com/kylechui/nvim-surround/discussions/141).

**Comment by kiyoon** [comment]
Thanks for your work, @kylechui .

Closing this in favour of `nvim-surround`. I think the difficulty of implementing this here is that it is the only exceptional text object that selects two different parts, so it won't work in visual mode. I think it makes sense to have a separate plugin that deals with this.
