### ISSUE TITLE
[R] textobject not working ... 

### ISSUE THREAD

**Issue by ipstone** [nvim-treesitter/nvim-treesitter-textobjects#214]
Hello, 

I am trying to get textobject working for R (in helix editor); but copying the textobjects.scm doesn't seem to work: though the editor reports the supporting of textobject, but it's not functional.

... any suggestions/help are much appreciated!

**Comment by kiyoon** [comment]
I know it's a bit late, but what do you mean you copied the scm file? You should rather use a plugin manager to install this plugin.
