### ISSUE TITLE
referenced JSX does not exist

### ISSUE THREAD

**Issue by danielo515** [nvim-treesitter/nvim-treesitter-textobjects#222]
**Language informations**

Hello, I noticed there is some references to the jsx language within the text objects files but I was not able to find that fule anywhere. Is it a mistake?

I have a couple of queries already for JSX, will you accept a PR?
Regards

**Comment by danielo515** [comment]
Hello, will you want to receive a PR or not?

**Comment by theHamsta** [comment]
This was probably a mistake. We would be happy to receive a PR!
