### ISSUE TITLE
Multiple move command

### ISSUE THREAD

**Issue by ofirgall** [nvim-treesitter/nvim-treesitter-textobjects#231]
Make move command accept `{count}` before them, like any other move in vim.

For example when configure `]a` to `goto_next_start` of `@paramater.inner`, `3]a` will jump to the 3rd parameter instead of using the same bind 3 times.

**Comment by danielo515** [comment]
Does this work for other actions? For example delete or change?

**Comment by danielo515** [comment]
Duplicate of #208
