### ISSUE TITLE
"index out of bounds". End of textobject can not be recognized if obj end with blankspace.

### ISSUE THREAD

**Issue by 66RING** [nvim-treesitter/nvim-treesitter-textobjects#256]
## **Describe the bug**

If there is a textobject, like funcion, at the end of file. And if there is no other character after it. The end of textobject can not be recognized. 

## **To Reproduce**

1. vim a.cpp
2. declare a function at the end
![image](https://user-images.githubusercontent.com/49358576/186448533-d23a7efa-bb0e-4c9a-b007-16eab57cda48.png)

3. use the "outer" filter, like keymaps `["af"] = "@function.outer"`
![image](https://user-images.githubusercontent.com/49358576/186448284-c5cd808a-b419-43b2-9e56-03da4b77159a.png)

5. type "vaf" in normal mode
6. error popup

![image](https://user-images.githubusercontent.com/49358576/186446391-b73af845-c14e-41ec-b609-c348767225b0.png)

Add any character after it fix this.

![image](https://user-images.githubusercontent.com/49358576/186446556-7beb2f8b-0d0a-4fcf-8517-1e6bc957935c.png)

## **Expected behavior**

textobject exactly it is with no additional blankspace, like this

![image](https://user-images.githubusercontent.com/49358576/186448834-978e1c2d-694a-4781-aad6-92515d26439d.png)

## **Output of `nvim --version`**

```
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR
-O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ring/var/APPs/neovim/build/cmake.config -I/home/ring/var/APPs/neovim/src -I/home/ring/var/APPs/neovim/.deps/usr/include -I/usr/include -I/home/ring/var/APPs/neovim/build/src/nvim/auto -I/home/ring/var/APPs/neovim/build/include
Compiled by ring@artix

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by cuongn265** [comment]
I switched back to 0.7 and it worked perfectly

**Comment by 66RING** [comment]
switched to recently update and it work fine. close for now.
