### ISSUE TITLE
@function.inner works for PHP, but this is not reflected in the README

### ISSUE THREAD

**Issue by laytan** [nvim-treesitter/nvim-treesitter-textobjects#266]
**Describe the bug**
@function.inner works for PHP, but this is not reflected in the README (the table entry is not green).

**To Reproduce**
1. Add configuration for select @function.inner
2. Open a PHP file
3. Execute a @function.inner command (delete around, for example)
4. It works

**Expected behavior**
The table cell to be green for @function.inner for the PHP row.

**Comment by theHamsta** [comment]
`@function.inner` does not appear directly in the parsed query https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/e581902a35f315b6998d8354d20cc4a0dfc0cf6e/queries/php/textobjects.scm#L13 instead only `"function.inner"` 

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/scripts/update-readme.lua would need to be updated for to recognize that.

**Comment by theHamsta** [comment]
Fix https://github.com/theHamsta/nvim-treesitter-textobjects/tree/fix-update-readme-script
