### ISSUE TITLE
Selection Command Completions Error

### ISSUE THREAD

**Issue by jamesb6626** [nvim-treesitter/nvim-treesitter-textobjects#288]
**Describe the bug**
Completions for `:TSTextobjectSelect` broke for me in 17e32b8.
Instead of the completions I got before then, `:TSTextobjectSelect<Space><Tab>` completes to `:TSTextobjectSelect -1` (no chooser), with the following error message:

```
Error detected while processing function nvim_treesitter_textobjects#available_textobjects:
line    1:
E5108: Error executing lua ...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:23: attempt to call field 'unpack' (a nil value)
stack traceback:
	...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:23: in function 'available_textobjects'
	[string "luaeval()"]:1: in main chunk
E714: List required
```

**To Reproduce**

Only treesitter and treesitter-textobjects required, reproduced with no other plugins (except vim-plug).
Simple treesitter config:
```
require 'nvim-treesitter.configs'.setup {
    textobjects = { select = { enable = true }, },
}
```
Edit a filetype with treesitter and textobjects support.
Remaining steps described in first section.

**Expected behavior**
Correct completions, as given in parent commit (reproduces in current master too).

**Output of `:checkhealth nvim-treesitter`**

<details>
<code>

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ .
  - cpp            ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Additional context**

**Comment by theHamsta** [comment]
Do you use Lua 5.3?

**Comment by theHamsta** [comment]
No, you have PUC Lua 5.1

**Comment by jamesb6626** [comment]
The PR fixes the issue for me, thanks. I'll let you close it with the PR.
I'm definitely going to switch to Lua 5.3 though, not sure how I ended up with 5.1 on this ubuntu 20.04 machine.
