### ISSUE TITLE
Error when neovim's height is less then `min_window_height`

### ISSUE THREAD

**Issue by boltlessengineer** [nvim-treesitter/nvim-treesitter-textobjects#315]
**Describe the bug**
Error below is printed when neovim's height is less than ts_context's `min_window_height` option.

```
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...start/nvim-treesitter-context/lua/treesitter-co
ntext.lua:738: attempt to call field 'close' (a nil value)
stack traceback:
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:738: in func
tion 'fn'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:481: in func
tion 'update'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:774: in func
tion <...start/nvim-treesitter-context/lua/treesitter-context.lua:772>
```

**To Reproduce**
1. Run neovim with following test.lua file `nvim -u test.lua --noplugin`
    ```
    require('treesitter-context').setup {
      min_window_height = 20,
    }
    ```
2. Resize neovim's height to be less then 20.
3. Open a file where you can see treesitter-context floating window.
4. Try to move cursor up or down (`j`, `k`, `H`, `L`...)
5. Error printed

**Expected behavior**
No error should be printed

**Output of `:checkhealth nvim-treesitter`**

<details>
<pre><code>nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.11.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - markdown_inline✓ . . . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}</code></pre>
</details>

**Output of `nvim --version`**
```
NVIM v0.9.0-dev-1423+gcc5b7368d-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by boltless@MacBook-Pro-3.local

Features: +acl +iconv +tui
See ":help feature-compile"

        시스템 vimrc 파일: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-cc5b736/share/nvim"

Run :checkhealth for more info
```

**Comment by kiyoon** [comment]
This issue seems to be related to nvim-treesitter-context.

**Comment by boltlessengineer** [comment]
Oh, your right. I accidentally wrote the issue in a totally wrong place.

Moving this issue to nvim-treesitter/nvim-treesitter-context#191.
