### ISSUE TITLE
[Custom Capture Help] `@function.name`, capture the function name from the current scope instead of lookahead/behind

### ISSUE THREAD

**Issue by ofirgall** [nvim-treesitter/nvim-treesitter-textobjects#328]
Hey, I'm trying to write a custom capture which captures the function name of the function I'm currently at instead of trying to lookahead.

This is the custom capture (golang):
```scm
;; Function name
(function_declaration
  name: (_)? @function.name)

(method_declaration
  name: (_)? @function.name)
```

**Comment by kiyoon** [comment]
Afaik, it cannot be done with the current version of this plugin. It will simply look ahead if the query is not found. This might be improved in the future to search from a given context (like you can search `@function.name` under the range of `@function.outer`.

Until then, I suggest you make a mapping like `[mvan` which will go to the beginning of the function and then select the name.

**Comment by kiyoon** [comment]
Closing as completed in #386
