### ISSUE TITLE
bind `<C-[>` will effect `<ESC>` in visual mode

### ISSUE THREAD

**Issue by NEX-S** [nvim-treesitter/nvim-treesitter-textobjects#338]
```lua
        move = {
            enable = true,
            goto_next_start = {
                ["<C-]>"] = "@function.outer"
            },
            goto_previous_start = {
                ["<C-[>"] = "@function.outer"
            },
        },
```
bind `<C-[>` will cause `<ESC>` can not work in visual mode, I guess is because treesitter-obj move-map is default `remap = true` ?

**Comment by kiyoon** [comment]
This is because Ctrl+[ is equivalent key to ESC. This is a vim's default behaviour, so don't map this key.
