### ISSUE TITLE
Even after enabling the plugin can't select the function

### ISSUE THREAD

**Issue by rustiever** [nvim-treesitter/nvim-treesitter-textobjects#34]
**Describe the bug**
I used python, go etc, but can't select or yank the function

**To Reproduce**
1. Install plugin
2. intall respective language
3. enable the plugin
4. can't use key- mapping like no effect In pressing the key mappings

**Expected behavior**
select or yank the function

**Output of `:checkhealth nvim_treesitter`**
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## clojure parser healthcheck
  - OK: clojure parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for clojure
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for clojure
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## ql parser healthcheck
  - OK: ql parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for ql
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for ql
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## graphql parser healthcheck
  - OK: graphql parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for graphql
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for graphql
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `indents.scm` found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## teal parser healthcheck
  - OK: teal parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## kotlin parser healthcheck
  - OK: kotlin parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for kotlin
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for kotlin
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for kotlin
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## turtle parser healthcheck
  - OK: turtle parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## gdscript parser healthcheck
  - OK: gdscript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for gdscript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for gdscript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## sparql parser healthcheck
  - OK: sparql parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## jsdoc parser healthcheck
  - OK: jsdoc parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## regex parser healthcheck
  - OK: regex parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## fennel parser healthcheck
  - OK: fennel parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for fennel
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for fennel
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
<details>
<code>

Paste the output here

</code>
</details>

**Comment by theHamsta** [comment]
Thanks for your report. Can you check whether the nvim-treesitter can find the textobject queries?
```
:lua print(vim.inspect(require'nvim-treesitter.query'.collect_group_results(0, 'textobject')))
```

There should also be commands to 
```
:TSTextobjectSelect @function.outer
```

The plugin has not yet implemented textobjects for injected languages. So js within an html document does not work at the moment.

**Comment by theHamsta** [comment]
@rustiever any updates on this? Can you call lua functions of this plugin? Can nvim-treesitter find the queries?

**Comment by rustiever** [comment]
now it is working properly 
I'm closing the issue
