### ISSUE TITLE
Allow linewise selection

### ISSUE THREAD

**Issue by echasnovski** [nvim-treesitter/nvim-treesitter-textobjects#36]
**Is your feature request related to a problem? Please describe.**
When attempting to make linewise selection of a textobject (for example, with `Vaf` for `function.outer`) I expect it to become linewise selection. Instead it is forced to be a regular selection (like an outcome of `vaf`). This is a consequence of how `nvim-treesitter.ts_utils.update_selection()` operates: it selects exactly the textobject forcing regular visual selection.

Linewise selection is useful, for example, when you want to delete lines with indented function definition.

**Describe the solution you'd like**
Making explicit linewise visual selection possible.

**Describe alternatives you've considered**
Technically, adding extra `V` keystroke solves the issue: `vafV` forces linewise selection. However, it seems to present a little unnecessary cognitive load compared to regular vim experience.

**Additional context**
I will make a PR which utilizes the equivalence of expected `Vaf` and `vafV`.

**Comment by theHamsta** [comment]
This feature sounds really useful! :-)

I don't know whether this should be fixed at our side as you described or whether the utility function could be extended.

**Comment by echasnovski** [comment]
I originally thought about updating the `nvim-treesitter.ts_utils.update_selection()`, but it seems to serve a different purpose. It directly updates current selection (if any) to match certain node exactly. As usages like `Vaf` and `dVaf` are about selecting and deleting certain textobjects I opted to making more targeted update in #37.

The `update_selection()` is also used elsewhere (like in `incremental_selection` submodule) which makes updating it a little bit more brittle.
