### ISSUE TITLE
Error on Fresh Boot Up

### ISSUE THREAD

**Issue by bhushan** [nvim-treesitter/nvim-treesitter-textobjects#388]
No matter what I tried, but I always get this error while doing fresh installation.

<img width="1418" alt="Screenshot 2023-02-11 at 10 25 44 PM" src="https://user-images.githubusercontent.com/43483545/218270639-fad793c7-3f69-46b1-8c2b-2b8fec76c0c2.png">

using it like this on neovim 0.8.3

```lua
use({
    "nvim-treesitter/nvim-treesitter-textobjects",
    requires = {
      "nvim-treesitter/nvim-treesitter",
    },
})
```

**Comment by kiyoon** [comment]
I think you need `after = "nvim-treesitter"` for packer or if you use lazy.nvim it doesn't happen.

**Comment by bhushan** [comment]
Thank you
