### ISSUE TITLE
nvim-treesitter.ts_utils.is_in_node_range is deprecated: use vim.treesitter.is_in_node_range

### ISSUE THREAD

**Issue by Bekaboo** [nvim-treesitter/nvim-treesitter-textobjects#391]
**Describe the bug**
API has changed. Please use `vim.treesitter.is_in_node_range`.

**Additional context**
The warning is due to a call to `nvim-treesitter.ts_utils.is_in_node_range` in `lua/nvim-treesitter/textobjects/shared.lua` line 94. Please use `vim.treesitter.is_in_node_range` instead.

**Comment by kiyoon** [comment]
Will be fixed soon. Thanks!

**Comment by kiyoon** [comment]
Closed as completed in #390
