### ISSUE TITLE
visual selections insert newlines rather than selecting

### ISSUE THREAD

**Issue by iHnR** [nvim-treesitter/nvim-treesitter-textobjects#392]
I have set up with the config found in the help page.

The builtin functions work well with `y`,`d`,`c`, but not with `v` or `V`. Typing `vif`,`vaf`,`vic`,`vac`, etc inserts newlines rather than selecting the block.

Because desctiptions are hard, I made a video. This shows a python function. I have confirmed the same behaviour on python classes and rust functions.

[Screencast from 13-02-23 00:41:39.webm](https://user-images.githubusercontent.com/62661051/218344329-b6888325-2e57-489b-a9f3-a3eafa5d16fc.webm)

**Comment by kiyoon** [comment]
Are you sure you're using the latest `nvim-treesitter`?

**Comment by leateng** [comment]
I also encountered this problem

**Comment by danarth** [comment]
I also had this exact same issue, but following @kiyoon's comment I updated `nvim-treesitter`. Now, visual selections work as expected!

I use vim-plug, so for me I just had to run `:PlugUpdate` and now it all works fine!

**Comment by kiyoon** [comment]
@iHnR Not sure about packer, but maybe you need to `:PackerCompile`?

Just make sure that the `nvim-treesitter` version is correctly up-to-date. Check the commit hash if it matches the newest version.

**Comment by kiyoon** [comment]
Seems to be a duplicate of #358

**Comment by iHnR** [comment]
@kiyoon Still persisting unfortunately :/

If I find the time, I'll check if it persists with a "clean" nvim install.

**Comment by kiyoon** [comment]
@iHnR  Maybe LunarVim adds checkpoint to `nvim-treesitter` to make it stable. So you need to manually check the version if it's updated or not. I think that will fix it.

**Comment by iHnR** [comment]
@kiyoon That was my guess. I'll snoop around and inform if I find something.

**Comment by kiyoon** [comment]
https://github.com/LunarVim/LunarVim/blob/fde46c4b163dfeb51407efdc2929cfc723fd15c6/snapshots/default.json#L89-L91

Notice how LunarVim keeps snapshot of some plugins. If you want to keep the old version, you also need to use the old version of `nvim-treesitter-textobjects`

**Comment by iHnR** [comment]
@kiyoon Thanks for your assistance. I have changed the snapshot to the latest commit. It works after changing the snapshot to the latest commit, then running `PackerSync` followed by `TSUpdateSync`.

**Comment by adibhanna** [comment]
I'm having a similar issue, even after updating the snapshot in lunarvim.
