### ISSUE TITLE
Implement move goto_current_end goto_current_start

### ISSUE THREAD

**Issue by vpeopleonatank** [nvim-treesitter/nvim-treesitter-textobjects#42]
For example, cursor is under `if` condition, I can navigate to the end or start of current `if` condition

**Comment by stsewd** [comment]
I think this is already supported https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move, I guess you only need to create a mapping for 

```
@conditional.outer
```

**Comment by cloggier** [comment]
Could that be used for somewhat smarter `%` replacement?

**Comment by vpeopleonatank** [comment]
> I think this is already supported https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move, I guess you only need to create a mapping for
> 
> ```
> @conditional.outer
> ```

With current available move option, i can map some keybinding to move goto_next_start then goto_previous_end to go to the end of current `if` condition. I think it 's a not smooth as some smart `%` behaviour like or goto_current_end option

**Comment by theHamsta** [comment]
The logic for textobject is very convoluted and could be drastically simplified by the `find_best_match` (although this function it self could be made more efficient) or extended by `find_best_match` when using textobjects with counts. I have not much time for this at the moment. So anyone is welcome to contribute!

**Comment by stsewd** [comment]
> I think it 's a not smooth as some smart % behaviour like or goto_current_end option

So, the % operator allows you to navigate between "ends" (if, else, endif, and go back to if).

Another feature would be to allow matching multiple objects with one keymap like:


```lua
    goto_next_start = {
        ["]m"] = "@function.outer | @class.outer | @conditional.outer",
      },
```

I'm not sure which ones your original issue is describing, but I'd like to have both anyway p:

**Comment by vpeopleonatank** [comment]
> So, the % operator allows you to navigate between "ends" (if, else, endif, and go back to if).

Is this % operator supported by nvim-treesitter, this is feature i want

**Comment by nkk1** [comment]
I am absolute beginner, I came up with

```
function GoToFunctionStart()
    local params = { textDocument = vim.lsp.util.make_text_document_params() }
    vim.lsp.buf_request(0, 'textDocument/documentSymbol', params, function(err, result, ctx, config)
        if err then
            print('Error when fetching document symbols: ' .. err.message)
            return
        end
        if result == nil then
            print('No symbols found')
            return
        end

        local line = vim.api.nvim_win_get_cursor(0)[1]
        local function_symbol = nil

        -- Filter out symbols to find the nearest function above the cursor
        for _, symbol in pairs(result) do
            if symbol.kind == 12 and symbol.range.start.line < line then
                if not function_symbol or function_symbol.range.start.line < symbol.range.start.line then
                    function_symbol = symbol
                end
            end
        end

        if function_symbol then
            -- Move cursor to the start of the function
            vim.api.nvim_win_set_cursor(0, {function_symbol.range.start.line + 1, function_symbol.range.start.character})
        else
            print("No function found above the cursor")
        end
    end)
end
```
