### ISSUE TITLE
Throw an error: 'get_capture_matches_recursively'

### ISSUE THREAD

**Issue by JiuRanYa** [nvim-treesitter/nvim-treesitter-textobjects#450]
**Describe the bug**
Install the `nvim-treesitter-textobjects`, use default config.

When I press 'v' + 'i' + 'f', it throw this error 
![image](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/58846658/86a8bd0f-5e82-4528-91a8-db84dbe34583)

**To Reproduce**

**Expected behavior**
Not error

**Output of `:checkhealth nvim-treesitter`**
![image](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/58846658/4173fe0a-d3a2-41f3-b1c9-916fb8d13e4a)

**Output of `nvim --version`**
```
Nvim v0.9.0
```

**Additional context**

**Comment by JiuRanYa** [comment]
> Did you install the recent commit of the textobjects and `nvim-treesitter`?

For sure. textobject and nvim-treesitter is lastest version.

**Comment by kiyoon** [comment]
It has been working fine for a while, and this is a very weird issue. I can't reproduce it. Interestingly, `shared.lua:238` is just an empty line. Maybe your installation went wrong?

**Comment by JiuRanYa** [comment]
> It has been working fine for a while, and this is a very weird issue. I can't reproduce it. Interestingly, `shared.lua:238` is just an empty line. Maybe your installation went wrong?

Thanks for your replay. I install it using `lazy.nvim`. I run `:Lazy` and all installation looks goes well.

**Comment by kiyoon** [comment]
Are you using preconfigured distro by any chance?

**Comment by JiuRanYa** [comment]
<img width="715" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/58846658/d2c64ded-5231-4c69-8655-4be7dd8b46db">

Here is my lazy.nvim installation config using textobjects default config.

**Comment by JiuRanYa** [comment]
● auto-save.nvim 1.53ms  VeryLazy
    ● bufferline.nvim 5.23ms  VeryLazy
    ● cmp-buffer 0.19ms   nvim-cmp
    ● cmp-cmdline 0.21ms   nvim-cmp
    ● cmp-nvim-lsp 0.22ms   nvim-cmp
    ● cmp-path 0.22ms   nvim-cmp
    ● cmp-vsnip 0.09ms   nvim-cmp
    ● fidget.nvim 0.46ms   nvim-lspconfig
    ● friendly-snippets 0.29ms   nvim-cmp
    ● gitsigns.nvim 6.08ms  start
    ● hop.nvim 1.79ms   config.keymaps
    ● indent-blankline.nvim 2.63ms  VeryLazy
    ● lazy.nvim 6.16ms   init.lua
    ● lspkind.nvim 0.13ms   nvim-cmp
    ● lspsaga.nvim 0.57ms  VeryLazy
    ● lualine.nvim 7.46ms  VeryLazy
    ● mason-lspconfig.nvim 0.17ms  VeryLazy
    ● mason.nvim 2.04ms  start
    ● mini.indentscope 1.07ms  VeryLazy
    ● neodev.nvim 16.53ms  VeryLazy
    ● neoformat 0.3ms  VeryLazy
    ● null-ls.nvim 6.37ms  VeryLazy
    ● nvim-autopairs 1.95ms   nvim-cmp
    ● nvim-base16 0.11ms  start
    ● nvim-cmp 19.51ms  start
    ● nvim-lspconfig 15.03ms   neodev.nvim
    ● nvim-surround 5.58ms  VeryLazy
    ● nvim-tree.lua 13.5ms  start
    ● nvim-treesitter 11.82ms   nvim-treesitter-context
    ● nvim-treesitter-context 14.72ms  VeryLazy
    ● nvim-treesitter-textobjects 8.91ms  VeryLazy
    ● nvim-ts-autotag 2.42ms  VeryLazy
    ● nvim-web-devicons 0.55ms   nvim-tree.lua
    ● plenary.nvim 0.73ms   null-ls.nvim
    ● toggleterm.nvim 3.04ms  VeryLazy
    ● vim-devicons 1.91ms  VeryLazy
    ● vim-illuminate 1.85ms  VeryLazy
    ● vim-tmux-navigator 0.46ms  VeryLazy
    ● vim-vsnip 4.15ms   nvim-cmp
    ● vim-vsnip-integ 0.43ms   nvim-cmp
    ● winbar.nvim 1.89ms  VeryLazy

This is all my plugins, looks not

> Are you using preconfigured distro (e.g. LunarVim) by any chance?

**Comment by kiyoon** [comment]
You're using the wrong repo. Please change the repo to the official one.
