### ISSUE TITLE
Can't use select and yank textobjects

### ISSUE THREAD

**Issue by vpeopleonatank** [nvim-treesitter/nvim-treesitter-textobjects#48]
**Describe the bug**
I used python, but can't select or yank the function with keybinding such as `v` or `y`. 
when put the cursor in a function, `:lua print(vim.inspect(require'nvim-treesitter.query'.collect_group_results(0, 'textobject')))`
return `{}`, but  use command like `:TSTextobjectSelect @function.outer` visually select all function
**To Reproduce**
1. Install plugin and python parser
2. Put cursor in python 's function
3. For example, press `vif` (which i binded `if` for ` "@function.inner"`) doesn't visually select inner function
**Expected behavior**
Press `vif` select inner function

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## Parser/Features H L F I

  - python         ✓ ✓ ✓ ✓ 

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+1186-g8665a96b9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az67-513

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**

**Comment by theHamsta** [comment]
Probably it will not work for buffer number 0. Can you try to get the current buffer number with nvim_get_current_buf or you use nil for buf. When the command works then the function should work to

**Comment by stsewd** [comment]
Can you share your config? This works for me

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all",
  textobjects = {
    select = {
      enable = true,
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
        ["ib"] = "@block.inner",
        ["ab"] = "@block.outer",
      },
    },
  },
}
```

Also, you can check `:map if`

**Comment by muarifer** [comment]
> Can you share your config? This works for me
> 
> ```lua
> require'nvim-treesitter.configs'.setup {
>   ensure_installed = "all",
>   textobjects = {
>     select = {
>       enable = true,
>       keymaps = {
>         ["af"] = "@function.outer",
>         ["if"] = "@function.inner",
>         ["ac"] = "@class.outer",
>         ["ic"] = "@class.inner",
>         ["ib"] = "@block.inner",
>         ["ab"] = "@block.outer",
>       },
>     },
>   },
> }
> ```
> 
> Also, you can check `:map if`

With this config, :map if says "No mapping found"
but Highlight, fold, indent and refactor works.

Here my sample config:

```vim
lua <<EOF
require'nvim-treesitter.configs'.setup {
	ensure_installed = "maintained",
	highlight= {
		enable = true,
	},
	indent = {
		enable = true,
	},
	refactor = {
		highlight_definitions = { enable = true },
		navigation = {
			enable = true,
			keymaps = {
				goto_definiton = "gnd",
				list_definitions = "gnD",
				list_definitions_toc = "gO",
				goto_next_usage = "<a-*>",
				goto_previous_usage = "<a-#>",
			},
		},
	},
	textobjects = {
    select = {
      enable = true,
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
        ["ib"] = "@block.inner",
        ["ab"] = "@block.outer",
      },
    },
  },
}
EOF

```

**Comment by vpeopleonatank** [comment]
> > Can you share your config? This works for me
> > ```lua
> > require'nvim-treesitter.configs'.setup {
> >   ensure_installed = "all",
> >   textobjects = {
> >     select = {
> >       enable = true,
> >       keymaps = {
> >         ["af"] = "@function.outer",
> >         ["if"] = "@function.inner",
> >         ["ac"] = "@class.outer",
> >         ["ic"] = "@class.inner",
> >         ["ib"] = "@block.inner",
> >         ["ab"] = "@block.outer",
> >       },
> >     },
> >   },
> > }
> > ```
> > 
> > 
> > Also, you can check `:map if`
> 
> With this config, :map if says "No mapping found"
> but Highlight, fold, indent and refactor works.
> 
> Here my sample config:
> 
> ```viml
> lua <<EOF
> require'nvim-treesitter.configs'.setup {
> 	ensure_installed = "maintained",
> 	highlight= {
> 		enable = true,
> 	},
> 	indent = {
> 		enable = true,
> 	},
> 	refactor = {
> 		highlight_definitions = { enable = true },
> 		navigation = {
> 			enable = true,
> 			keymaps = {
> 				goto_definiton = "gnd",
> 				list_definitions = "gnD",
> 				list_definitions_toc = "gO",
> 				goto_next_usage = "<a-*>",
> 				goto_previous_usage = "<a-#>",
> 			},
> 		},
> 	},
> 	textobjects = {
>     select = {
>       enable = true,
>       keymaps = {
>         ["af"] = "@function.outer",
>         ["if"] = "@function.inner",
>         ["ac"] = "@class.outer",
>         ["ic"] = "@class.inner",
>         ["ib"] = "@block.inner",
>         ["ab"] = "@block.outer",
>       },
>     },
>   },
> }
> EOF
> ```
> 
> **Edit:**
> It works.
> :map shows only in supported filetype.
> Also, after change keymaps, restart nvim and it'll works.

Probably I 'm in your case. How do you change keymaps? My `:map if` return `no mapping found`. How do you remap

**Comment by vpeopleonatank** [comment]
After remove duplicated line of code, my issue is solved.
