### ISSUE TITLE
Help create a jupyter-cell #%% text object for python files

### ISSUE THREAD

**Issue by drusmanbashir** [nvim-treesitter/nvim-treesitter-textobjects#487]
Hi I am newbie in lua and completely confused with text-objects. I have tried multiple ways to do this (including ChatGPT which failed ofc):

I use #%% inside my python files to quickly jump between code blocks. It also helps if i convert the .py file to .ipynb, in that it uses the #%% string to define cell boundaries in jupyter. Can you help create a tree-sitter text subject which recognises this pattern and a keymapping to help me jump from one occurence of #%% to next (and backwards)?

Thanks.

**Comment by kiyoon** [comment]
I implemented this feature without treesitter.

https://github.com/kiyoon/jupynium.nvim

You can use the plugin only for textobjects, or just take the textobjects code and modify as you need.

Also, in the plugin, I defined some queries for highlighting. If you don't need select and all you want is to move around, you can use the queries there that detects code cells etc.

**Comment by drusmanbashir** [comment]
You sir are a legend! By default the keybindings only work for *.ju.py files. How can I make it so it works in all .py files?
I will look at jupynium in detail. In the past, I was using jupyter_ascending to sync py with ipynb. I assume your plugin is more advanced than that.

**Comment by kiyoon** [comment]
Thank you! In the options there's a way to choose the file extension pattern you want to use!

**Comment by drusmanbashir** [comment]
I copy-pasted the init.lua file contents into my config and made this change:

function M.default_keybindings(augroup)
  vim.api.nvim_create_autocmd({ "BufWinEnter" }, {
    -- pattern = options.opts.jupynium_file_pattern,
    pattern = "*.py",
    callback = function(event)
      M.set_default_keymaps(event.buf)
    end,
    group = augroup,
  })
end


didn't work. It still only accepts *.ju.* pattern

**Comment by kiyoon** [comment]
```lua
require("jupynium").setup({
  jupynium_file_pattern = { "*.py" },
})
```

Can you try this?

**Comment by drusmanbashir** [comment]
Thank you that worked.
