### ISSUE TITLE
textobjects declaration feature request

### ISSUE THREAD

**Issue by singlexyz** [nvim-treesitter/nvim-treesitter-textobjects#49]
e.g.
@declaration.outer (the target is whole declaration)
<img width="267" alt="截屏2021-04-08 下午10 38 35" src="https://user-images.githubusercontent.com/4456413/114046267-493d6a00-98bb-11eb-9220-884aaf0aead0.png">

@declaration.inner (the target is whole value)
<img width="265" alt="截屏2021-04-08 下午10 38 50" src="https://user-images.githubusercontent.com/4456413/114046313-54909580-98bb-11eb-81c4-d001cca36baf.png">

and more like `const`, `var`, `let`, `window.value = 123`...

**Comment by theHamsta** [comment]
isn't the whole thing already included in `@statement..outer`? You're welcome to include language specific queries for JS or CSS. I personally don't use those languages.

**Comment by singlexyz** [comment]
> isn't the whole declaration already included in `@statement..outer`? You're welcome to include language specific queries for JS or CSS. I personally don't use those languages.
> 
> You can use nvim-treesitter/playground to experiment with the queries.

Thanks for reply 😄.
I figure how this plugin works, and here's the playground:
<img width="928" alt="截屏2021-04-14 上午8 40 46" src="https://user-images.githubusercontent.com/4456413/114639167-c162c000-9cff-11eb-88d9-1e252780f382.png">
I want to specify `value`, try different way and syntax, but always wrong, like:
```
(lexical_declaration
  (variable_declarator)
    value: (_) @function.inner) @function.outer
```
I am not familiar with this syntax 🥺，
Is this just a syntax error or limitation

**Comment by singlexyz** [comment]
Thank you so much!!!
Now it works, very useful.
