### ISSUE TITLE
Mapping repeating movements as recommended breaks some repeated commands

### ISSUE THREAD

**Issue by Mithrandir2k18** [nvim-treesitter/nvim-treesitter-textobjects#519]
**Describe the bug**
I've mapped repeat motions as described in the readme:
```
-- Optionally, make builtin f, F, t, T also repeatable with ; and ,
vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat_move.builtin_f)
vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat_move.builtin_F)
vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat_move.builtin_t)
vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat_move.builtin_T)
```
However now, when I want to repeat an action, such as `dt<space>` using `.`,
instead of repeating that action, I'm somehow in operator-pending mode
after pressing the dot. So to repeat `dt<space>` I have to press `.<space>`
instead of just `.`

Commenting these lines out fixed the issue for me as a workaround.

**To Reproduce**
Set the repeat movement binds [recommended in the Readme](https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move).
Try to repeat an action that includes these commands.
You'll find that the repeat command doesn't correctly reply
the specifier of the movement key (until which letter should it apply the action).

**Expected behavior**
Repeat the last action, without forgetting the last specifier.

**Output of `:checkhealth nvim-treesitter`**

<details>
<code>

nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.9-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905

```

**Comment by kiyoon** [comment]
Thanks for reporting it! In the function, it asks for an input first. We probably need to have a way to remap the dot repeatable function so that it remembers the last input.

**Comment by kiyoon** [comment]
@Mithrandir2k18 @sahinakkaya @ghostbuster91 
If you'd like to test the fix, I'd appreciate that.

You can install `"kiyoon/nvim-treesitter-textobjects"` with `branch = "fix/builtin_find"`

**Comment by Mithrandir2k18** [comment]
Oh, sry I totally missed that. Can confirm, this fixes it. Pushed my working config with the fix in my dotfiles linked above, included in the fix branch but also the master branch now. Thanks a lot!
