### ISSUE TITLE
Assignment operator do not exist for c/cpp

### ISSUE THREAD

**Issue by ilan-schemoul** [nvim-treesitter/nvim-treesitter-textobjects#585]
**Describe the bug**
TSTextobjectSelect do not work for assignement for c/cpp. It works for python.

**To Reproduce**
1. Go to a cpp file with any assignment such as `int ae = 42;`
2. Type command `TsTextobjectSelect @assignment.inner`
4. Nothing happens

**Expected behavior**
Inner assignment should be selected

**Output of `:checkhealth nvim-treesitter`**

<details>
<code>

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.146.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Thu Jan 11 04:09:03 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR vimdoc(highlights): ...Au8A/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 749 for language vimdoc
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/ilan/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...Au8A/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 749 for language vimdoc

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Additional context**
It works for python. All assignment operators (not just inside) fail to work on cpp.

**Comment by ilan-schemoul** [comment]
Hey it's doesn't work and the file it prompts to open is ~/.local/share/nvim/lazy/nvim-treesitter-textobjects/queries/cpp/textobjects.scm

**Comment by Akimcx** [comment]
That's the default one provided by `nvim-treesitter`. You should now that there's two version of the command

- `TSEditQuery` : which will open the file in `~/.local/share/nvim/lazy/nvim-treesitter-textobjects/queries/cpp/`
- `TSEditQueryUseAfter` : which will open `~/.config/nvim/after/queries/cpp/`

You have to use the later or if you really can't do it create the file manually

**Comment by ilan-schemoul** [comment]
I do not have TSEditQueryUseAfter but I have TSEditQueryUserAfter (note that I typed user instead of user)
`TSEditQueryUserAfter textobjects` which creates the file ~/.config/nvim/after/queries/cpp/textobjects.scm I copied pasted exactly what you provided. It still fails to work when it works with lua

**Comment by ilan-schemoul** [comment]
Okay so after I `InspectTree` I came up with this syntax which works : 
```
;; extends
(declaration
  declarator: (init_declarator
    declarator: (_) @assignment.lhs
    value: (_) @assignment.inner @assignment.rhs) @assignment.outer)

(declaration ; [1, 2] - [1, 11]
  type: (primitive_type) ; [1, 2] - [1, 5]
  declarator: (_) @assignment.inner) ; [1, 6] - [1, 10]
```

**Comment by ilan-schemoul** [comment]
On a related note it might be useful to have a syntax to select the type of an assignment ?
Like `int abc = 123;` @assignment.type could select int ?

**Comment by Akimcx** [comment]
> I do not have TSEditQueryUseAfter but I have TSEditQueryUserAfter (note that I typed user instead of user)

Yes my bad, this is the function you're supposed to use :)

**Comment by Akimcx** [comment]
> For the record treesitter syntax is not very hard (I just used :InspectTree to understand cpp file) :)

Yeah that, really cool

> Like int `abc = 123;` @assignment.type could select int ?

You can make that one, it the idea behind `TSEditQueryUserAfter`

**Comment by ilan-schemoul** [comment]
> You can make that one, it the idea behind TSEditQueryUserAfter

Yeah I added a @type. I was curious if you wanted to add something like this to this package ? But thinking about it maybe it's too much work and also many language don't have type. for the record if someone is interested what I did is `:TSEditQueryUserAfter textobjects` and pasted 
```scm
;;extends
(declaration
  type: (_) @type)

(parameter_declaration
  type: (_) @type)

(function_definition
  type: (_) @type)
```

**Comment by Akimcx** [comment]
Yup that's it, maybe you should mark this issue as closed now.

And since your it could take some time before your pr get merged into the project you can mark this as the solution. 

### Actual solution
open nvim and type `:TSEditQueryUserAfter textobjects`. in the created file paste this
```scm
;;extends
(declaration
  declarator: (init_declarator
    declarator: (_) @assignment.lhs
    value: (_) @assignment.rhs) @assignment.inner) @assignment.outer

(declaration
  type: (primitive_type)
  declarator: (_) @assignment.inner)

(expression_statement
  (assignment_expression
    left: (_) @assignment.lhs
    right: (_) @assignment.rhs) @assignment.inner) @assignment.outer
```
Nice pr btw 👍🏾

**Comment by ilan-schemoul** [comment]
I feel like it makes more sense to keep the issue open while the PR #587 is open (if another solution is commited I'll also close the issue) otherwise users will be misled into thinking this issue is solved when it is not.
If maintainers do not agree with this reasoning they can of course close this issue too.

**Comment by ilan-schemoul** [comment]
Merged

**Comment by Akimcx** [comment]
nice
