### ISSUE TITLE
Extra text objects for latex: environments, maths, and sections

### ISSUE THREAD

**Issue by tbdcit** [nvim-treesitter/nvim-treesitter-textobjects#596]
**Is your feature request related to a problem? Please describe.**
The text objects useful for a lot of programming languages (function, classes...) do not really make sense for latex. However, it would be very useful to take advantage of text objects when editing latex files.

**Describe the solution you'd like**
Add text objects for: inner/outer environments, inner/outer inline-math, inner/outer display-math, inner/outer section

**Describe alternatives you've considered**
The vimtex plugin which provides some of these features but requires disabling tree sitter.

**Comment by clason** [comment]
I'm sorry, but consistency is one of the primary goals of this project. If a language requires special captures, this is a strong indication that it should be handled by a dedicated plugin that installs custom queries.
