### ISSUE TITLE
flatten() requires a list-like table

### ISSUE THREAD

**Issue by sajjathossain** [nvim-treesitter/nvim-treesitter-textobjects#617]
**Describe the bug**
After updating treesitter to the newest commit I'm getting this error
![image](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/59532941/2de896a3-db5d-4f2c-8609-52a40b39c4f3)

**To Reproduce**
1. update treesitter
1. treesitter commit: `3d268f9db4e3b1bf8ba1de792407fe89ed1274db`
1. open neovim and you should see the error

**Expected behavior**
this error should not be there

**Output of `:checkhealth nvim-treesitter`**

<details>
<code>
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.7.3 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020"
} ~

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by 1466690577** [comment]
I get a same bug, it like this
<img width="1918" alt="屏幕截图 2024-05-18 004513" src="https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/32814641/57ce2c99-f0d8-4877-9763-a5a8253063ae">

**Comment by WhyNotHugo** [comment]
I bisected the nvim-treesitter plugin and the offending commit is 3d268f9db4e3b1bf8ba1de792407fe89ed1274db.

**Comment by nathanlaingzigzag** [comment]
I assume there is many ways to encounter this as it's going to depend on what tried to use tree-sitter objects first.

Here's mine
```
Failed to source `/Users/user/.local/share/nvim/lazy/nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim`
```
<img width="1707" alt="Screenshot 2024-05-17 at 5 53 12 PM" src="https://github.com/nvim-treesitter/nvim-treesitter-textobjects/assets/122106671/39bb7cc0-a141-46ce-9adf-ba8938836dd1">

**Comment by WhyNotHugo** [comment]
The following patch serves as a (hacky) workaround:

```diff
diff --git a/lua/nvim-treesitter/compat.lua b/lua/nvim-treesitter/compat.lua
index d4526c50..0773d3d3 100644
--- a/lua/nvim-treesitter/compat.lua
+++ b/lua/nvim-treesitter/compat.lua
@@ -29,11 +29,7 @@ function M.require_language(lang, opts)
 end
 
 function M.flatten(t)
-  if vim.fn.has "nvim-0.10" == 1 then
-    return vim.iter(t):flatten():totable()
-  else
     return vim.tbl_flatten(t)
-  end
 end
 
 return M
```

I don't really see what's wrong with the call to `:flatten`.

**Comment by Sunnova-ahmedrezk** [comment]
Looks like this PR [https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/609](url) is to fix the bug. But the checks failed.

**Comment by ahmed-rezk-dev** [comment]
Looks like this PR [https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/609](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/url) is to fix the bug. But the checks failed.

**Comment by milanglacier** [comment]
> The following patch serves as a (hacky) workaround:
> 
> ```diff
> diff --git a/lua/nvim-treesitter/compat.lua b/lua/nvim-treesitter/compat.lua
> index d4526c50..0773d3d3 100644
> --- a/lua/nvim-treesitter/compat.lua
> +++ b/lua/nvim-treesitter/compat.lua
> @@ -29,11 +29,7 @@ function M.require_language(lang, opts)
>  end
>  
>  function M.flatten(t)
> -  if vim.fn.has "nvim-0.10" == 1 then
> -    return vim.iter(t):flatten():totable()
> -  else
>      return vim.tbl_flatten(t)
> -  end
>  end
>  
>  return M
> ```
> 
> I don't really see what's wrong with the call to `:flatten`.

This is because iter:flatten behavior is different from `vim.tbl_flatten`, see this: https://github.com/neovim/neovim/issues/28777

**Comment by marcusandre** [comment]
I updated to the latest commit (https://github.com/nvim-treesitter/nvim-treesitter/commit/00a8cfd562dc805eb4d732fbca35e23640dbf7c8) a few minutes ago and the error doesn't show up any more. Have a lovely weekend, thanks for the fix, @clason. 👌

**Comment by eslam-allam** [comment]
I'm on that same commit but unfortunately still getting the same error:
```
lazy.nvim Failed to source `/home/eslamallam/.local/share/nvim/lazy/nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim`

vim/_editor.lua:0: nvim_exec2()../home/eslamallam/.local/share/nvim/lazy/nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim, line 3: Vim(lua):E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/iter.lua:236: flatten() requires a list-like table
stack traceback:
	[C]: in function 'error'
	/usr/share/nvim/runtime/lua/vim/iter.lua:236: in function 'flatten'
	...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/compat.lua:33: in function 'flatten'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/utils.lua:86: in function 'setup_commands'
	...eesitter-textobjects/lua/nvim-treesitter-textobjects.lua:70: in function 'init'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:485: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:484>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:484: in function 'source'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:443: in function 'source_runtime'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:411: in function 'packadd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:346: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:191: in function 'load'
	...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:55: in function 'load'
	...are/nvim/lazy/LazyVim/lua/lazyvim/plugins/treesitter.lua:89: in function <...are/nvim/lazy/LazyVim/lua/lazyvim/plugins/treesitter.lua:88>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - /LazyVim/lua/lazyvim/plugins/treesitter.lua:89
```

**Comment by hahuang65** [comment]
> I'm on that same commit but unfortunately still getting the same error:

Same here.

**Comment by clason** [comment]
The fix is only for stable; nightly will be fixed upstream.

**Comment by clason** [comment]
No, sorry. If you're on master, just wait for the Neovim PR to be merged.

**Comment by barrydevp** [comment]
Alright, I will make my workaround, thanks for your help 🤝

**Comment by Weyaaron** [comment]
I really appreciate the quick turnaround, I will do my best to give back with future my contributions :)

**Comment by rockyzhang24** [comment]
FYI: The upstream PR (https://github.com/neovim/neovim/pull/28781) has been merged and this issue was fixed on master.

**Comment by WhyNotHugo** [comment]
Thanks everyone for getting this fixed so quickly!
