### ISSUE TITLE
Solidity support request

### ISSUE THREAD

**Issue by zeroaddresss** [nvim-treesitter/nvim-treesitter-textobjects#651]
I've been using the navigation features a lot, which enhanced my coding experience.
However, I also use the **Solidity** programming language a lot and it was underwhelming to realize that it's not supported.
Unconsciously, I always try to `]m` and `yaf` then I realize that it won't work.

It would be greatly appreciated if you could add support for Solidity🙏🏻

**Comment by clason** [comment]
Queries are user-contributed; please send a PR.

**Comment by zeroaddresss** [comment]
> Queries are user-contributed; please send a PR.

Done!
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/665
