### ISSUE TITLE
Provide examples for every text object

### ISSUE THREAD

**Issue by nikitarevenco** [nvim-treesitter/nvim-treesitter-textobjects#679]
It would be helpful to have a vague idea of what each object exactly captures. We can give all examples in javascript, since we'd have pick 1 language to give examples in, and the greatest amount of developers are familiar with JS than any other language. For text objects that don't work in JS, we can use the 2nd or 3rd most known language.

**Comment by clason** [comment]
That's completely infeasible; the objects depend too much on the different languages.
