### ISSUE TITLE
Error in selecting a textobject

### ISSUE THREAD

**Issue by Futarimiti** [nvim-treesitter/nvim-treesitter-textobjects#680]
**Describe the bug**
Use an operator-pending keymap defined in `textobjects` entry e.g. `vif`, `vaf` in any file with TS enabled. An error will be thrown and nothing will be selected:
```
E5108: Error executing lua ...es/start/nvim-treesitter/lua/nvim-treesitter/tsrange.lua:27: attempt to call method 'start' (a nil value)
stack traceback:
        ...es/start/nvim-treesitter/lua/nvim-treesitter/tsrange.lua:27: in function 'from_nodes'
        ...ages/start/nvim-treesitter/lua/nvim-treesitter/query.lua:282: in function '(for generator)'
        ...ages/start/nvim-treesitter/lua/nvim-treesitter/query.lua:320: in function 'get_capture_matches'
        ...ages/start/nvim-treesitter/lua/nvim-treesitter/query.lua:445: in function 'fn'
        ...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:473: in function 'for_each_tree'
        ...ages/start/nvim-treesitter/lua/nvim-treesitter/query.lua:440: in function 'get_capture_matches_recursively'
        ...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:239: in function 'textobject_at_point'
        ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:103: in function 'select_textobject'
        [string ":lua"]:1: in main chunk
```

**To Reproduce**
1. Use this configuration
```lua
require('nvim-treesitter.configs').setup {
  ensure_installed = {},
  highlight = { enable = true },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = 'gnn',
      node_incremental = 'grn',
      scope_incremental = 'grc',
      node_decremental = 'grm',
    },
  },
  -- broken all times
  indent = { enable = false },
  textobjects = {
    select = {
      enable = true,
      lookahead = true,
      keymaps = {
        ['if'] = '@function.inner',
        ['af'] = '@function.outer',
        ['ic'] = '@class.inner',
        ['ac'] = '@class.outer',
        ['il'] = '@loop.inner',
        ['al'] = '@loop.outer',
        ['ia'] = '@parameter.inner',
        ['aa'] = '@parameter.outer',
      },
      selection_modes = {
        ['@parameter.outer'] = 'v',
        ['@function.outer'] = 'V',
        ['@class.outer'] = '<C-V>',
      },
      include_surrounding_whitespace = true,
    },
  },
}
```
2. Enter a file and enable TS on that buffer
3. Type `vif` (cursor position not matter)

**Expected behavior**
Within a function, `vif` should select the function body.

**Output of `:checkhealth nvim-treesitter`**

<details>
<code>
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - dhall               ✓ . ✓ . ✓
  - haskell             ✓ ✓ ✓ . ✓
  - haskell_persistent  ✓ . ✓ . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.11.0-nightly+b6e350a
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Additional context**
I use nix home-manager to manage plugins including nvim-treesitter and parsers; not sure if this would be relevant.

**Comment by clason** [comment]
Something is very broken in your installation then. This sounds like a Nix issue, which we can't help you with.
