### ISSUE TITLE
Change behaviour of @assignment.outer to include `local` and similar keywords

### ISSUE THREAD

**Issue by nikitarevenco** [nvim-treesitter/nvim-treesitter-textobjects#681]
Deleting an entire assignment is a common task and it would be nice to have a text object for that

New text object `@assignment.full` will capture the entire assignment. 

`[` and `]` denote what area the textobject will capture, if our cursor is at `*`

E.g. in javascript

```
[con*st foo = "foo";]
```
```js
[const bar = (bar) => "b*ar";]
```
```js
[const baz = function (str, num) {
  console.log(str)
  const obj = {
    str,
    num,
  }
retu*rn obj
};]
```

```js
const baz = function (str, num) {
  console.log(str)
  [const obj = {
    str,*
    num,
  };]
return obj
};
```

**Comment by clason** [comment]
1. Are there precedents in other editors?
2. How would the _query_ look? How many languages would this cover?

(Please no "pie in the sky" requests; we can only work within the limitations of tree-sitter queries.)

**Comment by nikitarevenco** [comment]
> 1. Are there precedents in other editors?
> 
>     2. How would the _query_ look? How many languages would this cover?
> 
> 
> (Please no "pie in the sky" requests; we can only work within the limitations of tree-sitter queries.)

Not sure about the first one, but i was able to create a basic implementation for javascript:

```

(lexical_declaration
  (variable_declarator
    name: (_) @assignment.lhs
    value: (_) @assignment.rhs)) @assignment.full

(variable_declaration
  (variable_declarator
    name: (_) @assignment.lhs
    value: (_) @assignment.rhs)) @assignment.full
```

**Comment by clason** [comment]
And what is the difference to `@assignment.outer`?

**Comment by nikitarevenco** [comment]
> And what is the difference to `@assignment.outer` (or just `@assignment`)?

Assuming our cursor is at `/**/` and denote the range with `[[]]`

`@assignment.outer`:

```js
const/**/[[foo = "foo"]];

const [[bar = (bar) => "b/**/ar"]];

const [[baz = function (str, num) {
  console.log(str);
  /**/
  const obj = {
    str,
    num,
  };

  return obj;
}]];
```

the new `@assignment.full` i made:

```
[[const/**/foo = "foo";]]

[[const bar = (bar) => "b/**/ar";]]

const baz = function (str, num) {
  console.log(str);
  /**/
  [[const obj = {
    str,
    num,
  };]]

  return obj;
};
```

**Comment by nikitarevenco** [comment]
Main difference is that it captures the keyword `const` as well as the semicolon at the end

**Comment by clason** [comment]
So the difference is not the assignment; you want to capture a full statement.

**Comment by nikitarevenco** [comment]
> So the difference is not the assignment; you want to capture a full statement.

There is a difference, for example if we wanted to capture an entire statement with this configuration:

```js
/**/function innerFunction() {
  if (true) {
    return "Inner return";
  }

  return null;
}

const result = outerFunction();
```

`@assignment.full` would capture the `const result ="outerFunction();`, but if we were to make a query for `@statement` (I am assuming this is how it would work, since `@statement` isn't even available for JS) then it would capture the function declaration and not the assignment

Allowing us to do lookahead operations

**Comment by clason** [comment]
You want `const result = outerFunction();`, don't you? That is a full statement.

**Comment by nikitarevenco** [comment]
If you want we can call it 

> You want `const result = outerFunction();`, don't you? That is a full statement.

By the way I agree that it's a full statement, if that isn't clear

But it's also a *subset* of a statement, more specific Statement than the general Statement

That's basically the main idea, would be useful to be able to operate specifically on `VariableDeclarationStatement` and not just `Statement`

**Comment by clason** [comment]
Then don't use `@statement` there. My point is that `@assignment.full` is _wrong_ for what you describe; _if_ a new textobject were added to capture it, it should be a version of `@statement`.

Otherwise this sounds way too niche to add and maintain here; you should just write your own personal query for it.

**Comment by nikitarevenco** [comment]
> Then don't use `@statement` there. My point is that `@assignment.full` is _wrong_ for what you describe; _if_ a new textobject were added to capture it, it should be a version of `@statement`.
> 
> Otherwise this sounds way too niche to add and maintain here; you should just write your own personal query for it.

Okay, we could call it something else

But it being niche? I don't know about that, The task of having to move/delete an entire assignment statement quite common, for me at least it's a lot more common than queries like `@conditional.inner` or `@conditional.outer`

**Comment by nikitarevenco** [comment]
Also I doubt this would be more niche than `@regex.inner` or `@regex.outer`, which are included in this repo

**Comment by kiyoon** [comment]
To me, I feel like modifying assignment.output to capture as you described would be an option.

**Comment by nikitarevenco** [comment]
> To me, I feel like modifying assignment.output to capture as you described would be an option.

Ok, I think that's a good idea. 

What about making `@assignment.inner` behave like `@assignment.outer` currently does, and making `@assignment.outer` behave like I described?

I am suggesting this since at the moment `@assignment.inner` captures the same region as `@assignment.lhs` or `@assignment.rhs`

But either approaches are fine and I can send a PR for `ecma` to modify `@assignment.outer`

**Comment by clason** [comment]
Well, we'd have to modify them _everywhere_ to stay consistent...

**Comment by nikitarevenco** [comment]
> Well, we'd have to modify them _everywhere_ to stay consistent...

I'm happy to do that

**Comment by nikitarevenco** [comment]
> Well, we'd have to modify them _everywhere_ to stay consistent...

Update: I have added the modifications for all languages that I know and that I have installed on my computer. If other people are familiar with the other feel free to submit contribution.

**Comment by kiyoon** [comment]
I already commented on the PR, but I object the idea of changing assignment.inner. I just think assignment.outer can be changed

**Comment by nikitarevenco** [comment]
Update: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/682#issuecomment-2335620132
