### ISSUE TITLE
Improve nix textobjects (assignment/attribute binding)

### ISSUE THREAD

**Issue by dwf** [nvim-treesitter/nvim-treesitter-textobjects#722]
**Is your feature request related to a problem? Please describe.**

Nix is fundamentally a language built around key/value attribute sets, but currently there's no text objects for the syntactic components of key/value binding in Nix.

**Describe the solution you'd like**
Some way to address left-hand side, right-hand side, and the entire `foo = bar` statement.

In my own config I am using

```
(binding
  attrpath: (_) @assignment.lhs
  expression: (_) @assignment.rhs @assignment.inner) @assignment.outer
```

This also captures bindings in a `let` block, which I am fine with for my own use, but it might be nice to have a way to differentiate the two (perhaps with `@attribute.outer` and `@attribute.inner`, and another for the lhs, `@attribute.name`?)

**Comment by clason** [comment]
Queries are user-contributed and best-effort. PRs are welcome.
