### ISSUE TITLE
Autojump to @inner from @outer

### ISSUE THREAD

**Issue by singlexyz** [nvim-treesitter/nvim-treesitter-textobjects#74]
In Vim, when you type a motion outside a textobj, it will auto jump forward then do the motion. 
This is super usefull, mean you don't need to move the cursor to the `textobj` part.

![ezgif-3-e88f11e678b7](https://user-images.githubusercontent.com/4456413/123678408-d966cc00-d878-11eb-8332-e9be5f6854ef.gif)

In `treesitter-textobjects`, it only do the motion when cursor in right position. 

For example below, the `@inner` is inside `@outer`.
When do the motion like `ca`, `da`, `ya`. It works good.
Cause cursor always in `@outer`

But the `@inner` part, have to move cursor it, then do the motion right.
 
<img width="399" alt="截屏2021-06-29 上午1 28 10" src="https://user-images.githubusercontent.com/4456413/123679169-c9032100-d879-11eb-8745-45ff536dd83f.png">

And here's the config, but I think has nothing to do with the config. 
```scm
; import
(import_statement
  (import_clause
    [(named_imports) (identifier)] @import.inner)) @import.outer
```

**Comment by theHamsta** [comment]
I think this already implemented with `lookahead = true` option
```
      textobjects = {
        select = {
          enable = true,
          lookahead = true,
        }
   }
```
However the documentation is missing. Would you mind creating a PR that explains this feature. I guess your figures are perfect to put them into the README.

**Comment by stsewd** [comment]
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/76 was already merged, thanks!
