### ISSUE TITLE
Is it possible to make parameter.outer take the previous comma, if there is no comma afterwards

### ISSUE THREAD

**Issue by IndianBoy42** [nvim-treesitter/nvim-treesitter-textobjects#85]
**Is your feature request related to a problem? Please describe.**
Given an argument list `A, B, C, D` the parameter.outer objects would be `A,`; `B,`; `C,` and `D`. This means that `daa` (delete around argument) would leave a trailing comma that has to be manually deleted

**Describe the solution you'd like**
It would be great if it could detect the last argument in the list specially and extend it backward to get the preceding comma

**Comment by theHamsta** [comment]
Certainly it would be possible. You would have to add an appropriate query for that. Have a look how parameter.outer is defined right now. You can use the `.` operator to select the last parameter.

Sorry, for this short explanation but I'm on mobile an scan give you more detailed information with code examples later
