### ISSUE TITLE
different approach to defining keybindings?

### ISSUE THREAD

**Issue by dlants** [nvim-treesitter/nvim-treesitter-textobjects#88]
**Is your feature request related to a problem? Please describe.**
A lot of the time when defining selections and movements, I run into conflicts with default vim bindings or other plugins. Debugging such situations is pretty tough, since the current way of configuring bindings (via the map) is opaque.

**Describe the solution you'd like**
Instead of creating bindings via the map, perhaps there's a way to expose the motions as commands, or some other format, where the user can assign them to bindings through a more standard mechanism, like `nvim_set_keymap`. For example, https://github.com/neovim/nvim-lspconfig defines a bunch of functions and asks users to create bindings via something like:

```
buf_set_keymap("n", "<leader>t", [[<Cmd>lua vim.lsp.buf.hover()<CR>]], opts)
```

I think this is pretty straightforward for things like "move" commands, but I'm not sure whether it will work for things like "select".

**Comment by theHamsta** [comment]
All possible actions should now be able as commands that you can conveniently map

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/20

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/21

**Comment by stsewd** [comment]
This is already possible, see

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/f51c3feb5abe1dea556c9076b8a8928d3bf56790/lua/nvim-treesitter/textobjects/select.lua#L61-L64

for examples of defining operator pending mappings
