### ISSUE TITLE
Feature request: extend swap functionality to also work on comma separated lists

### ISSUE THREAD

**Issue by Melkster** [nvim-treesitter/nvim-treesitter-textobjects#89]
nvim-treesitter-textobjects has the the ability to [swap function arguments](https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-swap). I have previously been using [vim-argumentative](https://github.com/PeterRincker/vim-argumentative), which also does this (without the use of tree-sitter). However, vim-argumentative is also able to swap the positions of items in lists. For instance, with the cursor on item `foo` in the following example, pressing `>,` moves `foo` from the first index to the second one like so: `[foo, bar, baz]` --> `[bar, foo, baz]`.

Would this be possible to impement using tree-sitter?

I personally use the following config for swap:

```lua
swap = {
  enable = true,
  swap_next = {
    ['>,'] = '@parameter.inner',
  },
  swap_previous = {
    ['<,'] = '@parameter.inner',
  }
}
```

What I would want is for `>,` to swap both parameters and list items like in my previous example.

Edit: I realized after posting that #86 is a very similar question.

**Comment by stsewd** [comment]
This is already possible on some languages https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/87. Discussion is open to have those as a separate capture group at https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/86.
