### ISSUE TITLE
vim-commentary can comment out functions and classes, but not uncomment them

### ISSUE THREAD

**Issue by David-Else** [nvim-treesitter/nvim-treesitter-textobjects#90]
I assume this is a bug in this extension rather than `vim-commentary`, but I don't know that. Please close if it is not.

Commenting in and out code is a PERFECT use of this extension, I hope it can be made to work.

**Describe the bug**
Using https://github.com/tpope/vim-commentary I can comment out a class or a function with `gcac gcaf` but when I repeat the command it does not uncomment it. This is the expected behaviour of `vim-commentary`.

**To Reproduce**
Try it with vim-commentary on any TypeScript file.

**Output of `:checkhealth nvim_treesitter`**

<details>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.16.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - bash           ✓ ✓ ✓ . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by theHamsta** [comment]
Does it depend on `:h syntax`? You can check with `:set syntax=on`

**Comment by David-Else** [comment]
I don't think i has anything to do with `:set syntax=on`. I tried with on and off. I extension is only 100 lines, it should be easy to see what it does https://github.com/tpope/vim-commentary/blob/master/plugin/commentary.vim

For example:
```ts
function example(): number {
  return 42;
}
```
I can comment it on and off as a sentence with `gcas`, but as a function `gcaf` it only toggles on, not off again.

**Comment by gegoune** [comment]
Does treesitter even know that commented out code is a function? I tried that with https://github.com/terrortylor/nvim-comment and it comments function right but won't properly uncomment it.

You can try to do something like:
`gcaf` to comment function
on commented out block do:
`vaf` to see that it is not visually selecting around function as you would expect. It is then just commented something, rather than code.

**Comment by David-Else** [comment]
I tried `vaf`, it no longer knows it is a function! I thought that might be the case.

I am not sure the best way to solve this. I tried the `@comment.outer` functionality in TypeScript, but unfortunately it seems to do nothing. I assume the ultimate solution is that treesiiter knows what is inside a comment, and can act on that somehow.
