### ISSUE TITLE
Add string textobject

### ISSUE THREAD

**Issue by figsoda** [nvim-treesitter/nvim-treesitter-textobjects#99]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have string textobjects so I can e.g. replace the content of a string with my clipboard

**Describe the solution you'd like**
`@string.outer` that includes the quotes and `@string.inner` that doesn't include the quotes

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kuator** [comment]
Don't `vi"` and `va"` work already?

**Comment by figsoda** [comment]
didn't know they existed. Thanks! They could be still a generalized version based on treesitter but thats `vi"` does what I wanted.
